services:
  planner:
    image: old_planner_api
    depends_on:
      - planner-db
    ports:
      - 8888:8888
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=planner-db;Port=5432;Database=planner;Username=postgres;Password=postgres
    volumes:
      - Resources:/Resources
      - data-protection-keys:/keys

  planner-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=planner
    ports:
      - "5434:5432"
    volumes:
      - postgres-planner-data:/var/lib/postgresql/data

volumes:
  postgres-planner-data:
  Resources:
  data-protection-keys: